### ISSUE TITLE
Error "array must contain integer values" in ocropus-gpageseg with uint64

### ISSUE THREAD

**Issue by mrfortynine** [tmbdev/ocropy#35] opened 2015-05-08 02:37 UTC
Hello,

I'm trying to run the test script on OS X 10.10 with python 2.7. An exception is throw at the second step running ocropus-gpageseg. 

```
MacBook-Pro-2:ocropy pujia$ PATH=$PATH:. ./run-test 
# tests/testpage.png
=== tests/testpage.png 1
estimating skew angle
estimating thresholds
rescaling
tests/testpage.png lo-hi (0.39 1.44) angle  0.1  no-normalization
writing

########## ./ocropus-gpageseg temp/????.bin.png

temp/0001.bin.png
Traceback (most recent call last):
  File "./ocropus-gpageseg", line 414, in safe_process1
    process1(job)
  File "./ocropus-gpageseg", line 356, in process1
    scale = psegutils.estimate_scale(binary)
  File "/Users/pujia/git-workspace/ocropy/ocrolib/psegutils.py", line 41, in estimate_scale
    objects = binary_objects(binary)
  File "/Users/pujia/git-workspace/ocropy/ocrolib/psegutils.py", line 37, in binary_objects
    objects = morph.find_objects(labels)
  File "/Users/pujia/git-workspace/ocropy/ocrolib/toplevel.py", line 209, in argument_checks
    raise e
CheckError: 
CheckError for argument image of function <function find_objects at 0x103972398>
<ndarray-7fbead2b6420 (3000, 2078) uint64 [0,5187]> of type <type 'numpy.ndarray'>: array must contain integer values

########## ./ocropus-rpred -n temp/????/??????.bin.png

Traceback (most recent call last):
  File "./ocropus-rpred", line 92, in <module>
    inputs = ocrolib.glob_all(args.files)
  File "/Users/pujia/git-workspace/ocropy/ocrolib/toplevel.py", line 213, in argument_checks
    result = f(*args,**kw)
  File "/Users/pujia/git-workspace/ocropy/ocrolib/common.py", line 654, in glob_all
    raise FileNotFound("%s: expansion did not yield any files"%arg)
ocrolib.common.FileNotFound: file not found temp/????/??????.bin.png: expansion did not yield any files
```

I just want to check to see if this issue is known before I start debug from bottom up. Thanks.

**Comment by tmbdev** [comment] 2015-06-05 09:26
Some of the morphology functions in scipy.ndimage take only a restricted set of types, and that set seems to be platform dependent. I'm not sure what a portable solution to that problem is. You could add a line that coerces the image to the right type just for OS X. If you find a portable solution, please share it.

**Comment by jmokoistinen** [comment] 2015-11-14 10:35
I have the same problem? I am using Ubuntu 14.04.3 LTS

INFO:  ########## /usr/local/bin/ocropus-rpred -n temp/????/??????.bin.png
INFO:  
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rpred", line 98, in <module>
    inputs = ocrolib.glob_all(args.files)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/toplevel.py", line 213, in argument_checks
    result = f(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/common.py", line 654, in glob_all
    raise FileNotFound("%s: expansion did not yield any files"%arg)

**Comment by bbiglari** [comment] 2015-12-11 20:15
@tmbdev can you tell me how to do so? Thanks

**Comment by bbiglari** [comment] 2015-12-11 20:15
@mrfortynine can you please share your solution with me as well? Thanks

**Comment by mrfortynine** [comment] 2015-12-13 23:04
> @mrfortynine can you please share your solution with me as well? Thanks

Sorry, I have not continued pursuing this.

**Comment by Halfish** [comment] 2016-01-29 06:46
I got the same error too, how did you fix this at that time?

**Comment by kba** [comment] 2017-12-11 23:24
@jmokoistinen's problem probably unrelated, missing the binarized images could be for many reasons.

If this is a consistent problem, it would be helpful to have further details on system configuration and library versions like scipy to reproduce it.

**Comment by zuphilip** [comment] 2017-12-25 17:30
The original issue was fixed in https://github.com/tmbdev/ocropy/commit/9be1ae0eeae8772316fc5c3f354e44d3bf98089c . Any other report here could be caused by another reason. Please update to the newest version and try again. If your problem persists, then open a **new** issue including your error traceback.

**Closed by zuphilip** 2017-12-25 17:30 UTC
