### ISSUE TITLE
ocopus-econf fails for empty text

### ISSUE THREAD

**Issue by stweil** [tmbdev/ocropy#167] opened 2017-01-05 08:31 UTC
The latest version of ocopus-econf fails to produce output for empty text:

    # touch test.gt.txt test.txt
    # ocropus-econf --kind nospace test.gt.txt
    Traceback (most recent call last):
      File "/usr/local/bin/ocropus-econf", line 59, in <module>
        outputs = sorted(list(outputs))
      File "/usr/local/lib/python2.7/dist-packages/ocrolib/common.py", line 563, in parallel_map
        for e in pool.imap_unordered(fun,jobs,chunksize):
      File "/usr/lib/python2.7/multiprocessing/pool.py", line 287, in <genexpr>
        return (item for chunk in result for item in chunk)
      File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
        raise value
    UnboundLocalError: local variable 'current' referenced before assignment

**Comment by zuphilip** [comment] 2017-01-05 08:42
This is a duplicate of #45 and I suggested a fix in #131. Can you confirm that the fix works?

**Closed** 2017-01-10 20:26 UTC
Labels: duplicate
